<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pets')->insert([
            [
                'user_id' => 3,
                'name' => 'Lucy',
                'breed' => 'Shih Tzu',
                'gender' => 'Female',
                'birthday' => '2020-02-14',
                'image' => 'img/pets/pett31.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-06-30',
            ],
            [
                'user_id' => 3,
                'name' => 'Gizmo',
                'breed' => 'Chinchilla',
                'gender' => 'Male',
                'birthday' => '2021-04-22',
                'image' => 'img/pets/pett37.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-09-10',
            ],

            [
                'user_id' => 3,
                'name' => 'Maggie',
                'breed' => 'Bichon Frise',
                'gender' => 'Female',
                'birthday' => '2019-03-30',
                'image' => 'img/pets/pett34.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-08-15',
            ],
            [
                'user_id' => 1,
                'name' => 'Fluffy',
                'breed' => 'Persian',
                'gender' => 'Female',
                'birthday' => '2020-01-01',
                'image' => 'img/pets/pet1.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-01-01',
            ],
            [
                'user_id' => 2,
                'name' => 'Buddy',
                'breed' => 'Labrador',
                'gender' => 'Male',
                'birthday' => '2019-05-15',
                'image' => 'img/pets/pet2.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-02-01',
            ],
            [
                'user_id' => 3,
                'name' => 'Rose',
                'breed' => 'Himalayan',
                'gender' => 'Female',
                'birthday' => '2021-03-20',
                'image' => 'img/pets/pett3.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-03-15',
            ],
            [
                'user_id' => 4,
                'name' => 'Rocky',
                'breed' => 'Beagle',
                'gender' => 'Male',
                'birthday' => '2018-11-10',
                'image' => 'img/pets/re8.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-04-10',
            ],
            [
                'user_id' => 5,
                'name' => 'Tweety',
                'breed' => 'Canary',
                'gender' => 'Female',
                'birthday' => '2022-08-12',
                'image' => 'img/pets/re6.jpg',
                'animal_type_id' => 3,
                'last_vaccination_date' => '2024-05-05',
            ],
            [
                'user_id' => 6,
                'name' => 'Max',
                'breed' => 'German Shepherd',
                'gender' => 'Male',
                'birthday' => '2017-02-01',
                'image' => 'img/pets/re4.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-06-01',
            ],
            [
                'user_id' => 4,
                'name' => 'Bella',
                'breed' => 'Golden Retriever',
                'gender' => 'Female',
                'birthday' => '2020-12-15',
                'image' => 'img/pets/re3.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-07-10',
            ],
            [
                'user_id' => 5,
                'name' => 'Charlie',
                'breed' => 'Siberian Husky',
                'gender' => 'Male',
                'birthday' => '2019-07-04',
                'image' => 'img/pets/re1.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-08-20',
            ],
            [
                'user_id' => 6,
                'name' => 'Luna',
                'breed' => 'Maine Coon',
                'gender' => 'Female',
                'birthday' => '2021-05-21',
                'image' =>'img/pets/donate1.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-09-15',
            ],
            [
                'user_id' => 10,
                'name' => 'Daisy',
                'breed' => 'Pug',
                'gender' => 'Female',
                'birthday' => '2018-03-17',
                'image' => 'img/pets/pet10.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-10-05',
            ],
            [
                'user_id' => 11,
                'name' => 'Oscar',
                'breed' => 'Chihuahua',
                'gender' => 'Male',
                'birthday' => '2021-11-30',
                'image' => 'img/pets/pet11.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-11-10',
            ],
            [
                'user_id' => 12,
                'name' => 'Milo',
                'breed' => 'Rottweiler',
                'gender' => 'Male',
                'birthday' => '2017-04-19',
                'image' => 'img/pets/pet12.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-12-01',
            ],
            [
                'user_id' => 13,
                'name' => 'Nina',
                'breed' => 'Sphynx',
                'gender' => 'Female',
                'birthday' => '2022-09-12',
                'image' => 'img/pets/pet13.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-12-20',
            ],
            [
                'user_id' => 14,
                'name' => 'Zoe',
                'breed' => 'Scottish Fold',
                'gender' => 'Female',
                'birthday' => '2020-10-10',
                'image' => 'img/pets/pet14.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-10-15',
            ],
            [
                'user_id' => 15,
                'name' => 'Buddy',
                'breed' => 'Doberman',
                'gender' => 'Male',
                'birthday' => '2018-06-30',
                'image' => 'img/pets/pet15.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-01-11',
            ],
            [
                'user_id' => 16,
                'name' => 'Ginger',
                'breed' => 'Cocker Spaniel',
                'gender' => 'Female',
                'birthday' => '2019-01-25',
                'image' => 'img/pets/pet16.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-02-14',
            ],
            [
                'user_id' => 17,
                'name' => 'Toby',
                'breed' => 'Chinchilla',
                'gender' => 'Male',
                'birthday' => '2021-05-18',
                'image' => 'img/pets/pet17.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-03-03',
            ],
            [
                'user_id' => 18,
                'name' => 'Kiki',
                'breed' => 'Siamese',
                'gender' => 'Female',
                'birthday' => '2020-12-25',
                'image' => 'img/pets/pet18.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-03-20',
            ],
            [
                'user_id' => 19,
                'name' => 'Bella',
                'breed' => 'Bulldog',
                'gender' => 'Female',
                'birthday' => '2019-11-11',
                'image' => 'img/pets/pet19.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-04-04',
            ],
            [
                'user_id' => 20,
                'name' => 'Loki',
                'breed' => 'Great Dane',
                'gender' => 'Male',
                'birthday' => '2017-09-07',
                'image' => 'img/pets/pet20.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-05-12',
            ],
            [
                'user_id' => 21,
                'name' => 'Lucy',
                'breed' => 'Shih Tzu',
                'gender' => 'Female',
                'birthday' => '2020-02-14',
                'image' => 'img/pets/pet21.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-06-30',
            ],
            [
                'user_id' => 22,
                'name' => 'Rocky',
                'breed' => 'Akita',
                'gender' => 'Male',
                'birthday' => '2018-10-05',
                'image' => 'img/pets/pet22.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-07-20',
            ],
            [
                'user_id' => 23,
                'name' => 'Maggie',
                'breed' => 'Bichon Frise',
                'gender' => 'Female',
                'birthday' => '2019-03-30',
                'image' => 'img/pets/pet23.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-08-15',
            ],
            [
                'user_id' => 24,
                'name' => 'Gizmo',
                'breed' => 'Chinchilla',
                'gender' => 'Male',
                'birthday' => '2021-04-22',
                'image' => 'img/pets/pet24.jpg',
                'animal_type_id' => 4,
                'last_vaccination_date' => '2024-09-10',
            ],

            [
                'user_id' => 3,
                'name' => 'Ginger',
                'breed' => 'Cocker Spaniel',
                'gender' => 'Female',
                'birthday' => '2019-01-25',
                'image' => 'img/pets/pett33.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-02-14',
            ],
            [
                'user_id' => 3,
                'name' => 'Toby',
                'breed' => 'Shinshilla',
                'gender' => 'Male',
                'birthday' => '2021-05-18',
                'image' => 'img/pets/pett27.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-03-03',
            ],
            [
                'user_id' => 3,
                'name' => 'lory',
                'breed' => 'Siamese',
                'gender' => 'Female',
                'birthday' => '2020-12-25',
                'image' => 'img/pets/pett28.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-03-20',
            ],
            [
                'user_id' => 3,
                'name' => 'Bell',
                'breed' => 'Bulldog',
                'gender' => 'male',
                'birthday' => '2019-11-11',
                'image' => 'img/pets/pett29.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-04-04',
            ],
            [
                'user_id' => 3,
                'name' => 'Loki',
                'breed' => 'Great Dane',
                'gender' => 'Male',
                'birthday' => '2017-09-07',
                'image' => 'img/pets/pett30.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-05-12',
            ],

            [
                'user_id' => 3,
                'name' => 'Rocky',
                'breed' => 'Akita',
                'gender' => 'Male',
                'birthday' => '2018-10-05',
                'image' => 'img/pets/ro.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-07-20',
            ],

            [
                'user_id' => 3,
                'name' => 'Lola',
                'breed' => 'Goldfish',
                'gender' => 'Female',
                'birthday' => '2022-06-17',
                'image' => 'img/pets/pett38.jpg',
                'animal_type_id' => 4,
                'last_vaccination_date' => '2024-10-05',
            ],
            [
                'user_id' => 3,
                'name' => 'Fluffy',
                'breed' => 'Persian',
                'gender' => 'Female',
                'birthday' => '2020-01-01',
                'image' => 'img/pets/pett1.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-01-01',
            ],
            [
                'user_id' => 3,
                'name' => 'Buddy',
                'breed' => 'Labrador',
                'gender' => 'Male',
                'birthday' => '2019-05-15',
                'image' => 'img/pets/pett2.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-02-01',
            ],
            [
                'user_id' => 3,
                'name' => 'Oscar',
                'breed' => 'Chihuahua',
                'gender' => 'Male',
                'birthday' => '2021-11-30',
                'image' => 'img/pets/pet111.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-11-10',
            ],
            [
                'user_id' => 3,
                'name' => 'Zoe',
                'breed' => 'Scottish Fold',
                'gender' => 'Female',
                'birthday' => '2020-10-10',
                'image' => 'img/pets/pett114.jpg',
                'animal_type_id' => 1,
                'last_vaccination_date' => '2024-10-15',
            ],
            [
                'user_id' =>3,
                'name' => 'Milo',
                'breed' => 'Rottweiler',
                'gender' => 'Male',
                'birthday' => '2017-04-19',
                'image' => 'img/pets/pett112.jpg',
                'animal_type_id' => 2,
                'last_vaccination_date' => '2024-12-01',
            ],
            [
                'user_id' => 25,
                'name' => 'Lola',
                'breed' => 'Goldfish',
                'gender' => 'Female',
                'birthday' => '2022-06-17',
                'image' => 'img/pets/pet25.jpg',
                'animal_type_id' => 4,
                'last_vaccination_date' => '2024-10-05',
            ],



            // [
            //     'user_id' => 3,
            //     'name' => 'Polly',
            //     'breed' => 'African Grey',
            //     'gender' => 'Male',
            //     'birthday' => '2020-03-10',
            //     'image' => 'img/pets/pett36.jpg',
            //     'animal_type_id' => 8,
            //     'last_vaccination_date' => '2023-08-25',
            // ],
            // [
            //     'user_id' => 3,
            //     'name' => 'Kiwi',
            //     'breed' => 'Macaw',
            //     'gender' => 'Female',
            //     'birthday' => '2019-07-14',
            //     'image' => 'img/pets/pett37.jpg',
            //     'animal_type_id' => 8,
            //     'last_vaccination_date' => '2023-06-18',
            // ],
            // [
            //     'user_id' => 3,
            //     'name' => 'Rio',
            //     'breed' => 'Cockatoo',
            //     'gender' => 'Male',
            //     'birthday' => '2018-11-30',
            //     'image' => 'img/pets/pett38.jpg',
            //     'animal_type_id' => 8,
            //     'last_vaccination_date' => '2024-01-10',
            // ]
        ]);
    }
}
